#!/usr/bin/env python3
"""Pydantic DTOs to the browser's TypeScript types. Never hand-edit the output.

The models are the single source of truth for three things at once: what the
CLI writes to JSON, what the API answers with, and what the browser types
against. Generating the third from the first is what stops them drifting.

`--check` regenerates and fails on any difference, which is how `just check`
catches a model change that nobody propagated.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "frontend" / "src" / "generated" / "contracts.ts"

HEADER = """// Generated by tools/export_contracts.py from the backend's Pydantic models.
// Do not edit. Run `just contracts` after changing backend/src/reposhape/models.py.
"""


def _render() -> str:
    """Build the TypeScript by walking the models rather than shelling out.

    A JSON-Schema-to-TypeScript generator would pull a second toolchain in for
    eleven flat models. Walking Pydantic's own fields keeps the dependency
    surface at zero and the output readable.
    """
    from pydantic import BaseModel

    from reposhape import models

    # Derived, not listed. A hand-maintained list silently omits a model the
    # moment one is added, and the failure surfaces as a missing TypeScript
    # export rather than as anything pointing at this file.
    exported = [
        value
        for value in vars(models).values()
        if isinstance(value, type)
        and issubclass(value, BaseModel)
        and value is not BaseModel
        and value.__module__ == models.__name__
    ]
    exported.sort(key=lambda model: model.__name__)

    # Literal aliases are derived the same way and for the same reason: the
    # three that used to be listed here by hand were the three that existed the
    # day this was written, and `AnalysisSource` was added without anyone
    # noticing the list.
    from typing import Literal, get_origin

    aliases = [
        (name, value)
        for name, value in vars(models).items()
        if not name.startswith("_") and get_origin(value) is Literal
    ]
    aliases.sort()

    lines = [HEADER]
    for name, alias in aliases:
        lines.append(f"export type {name} = {_union(alias)};")
    lines.append("")

    for model in exported:
        lines.append(f"export interface {model.__name__} {{")
        for name, field in model.model_fields.items():
            lines.append(f"  {name}: {_typescript(field.annotation)};")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def _union(literal_alias: object) -> str:
    from typing import get_args

    return " | ".join(f'"{value}"' for value in get_args(literal_alias))


def _typescript(annotation: object) -> str:
    import datetime
    import types
    from typing import Literal, get_args, get_origin

    if annotation is str:
        return "string"
    if annotation is int or annotation is float:
        return "number"
    if annotation is bool:
        return "boolean"
    if annotation is datetime.datetime:
        return "string"
    if annotation is type(None):
        return "null"

    origin = get_origin(annotation)
    if origin is Literal:
        return " | ".join(f'"{value}"' for value in get_args(annotation))
    if origin in (list, set, tuple):
        return f"{_typescript(get_args(annotation)[0])}[]"
    if origin is dict:
        key, value = get_args(annotation)
        return f"Record<{_typescript(key)}, {_typescript(value)}>"
    if origin in (types.UnionType,) or str(origin) == "typing.Union":
        return " | ".join(_typescript(arg) for arg in get_args(annotation))

    if hasattr(annotation, "model_fields"):
        return annotation.__name__
    raise TypeError(f"no TypeScript mapping for {annotation!r}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the output is stale.")
    args = parser.parse_args()

    rendered = _render()
    if args.check:
        if not OUTPUT.is_file():
            print(f"missing {OUTPUT}. Run: just contracts", file=sys.stderr)
            return 1
        if OUTPUT.read_text(encoding="utf-8") != rendered:
            print(
                f"{OUTPUT} is stale. The backend models changed and the contract was not "
                "regenerated. Run: just contracts",
                file=sys.stderr,
            )
            subprocess.run(["git", "--no-pager", "diff", "--stat", "--", str(OUTPUT)], check=False)
            return 1
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
